---
.github/workflows/ci.yaml:
  unit_name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
  unit_includes:
    - ruby: '2.4.9'
      puppet: '5'
      fixtures: .fixtures-latest.yml
      allow_failure: true
    - ruby: '2.5.7'
      puppet: '6'
      fixtures: .fixtures-latest.yml
      allow_failure: true
  acceptance_name: '${{ matrix.puppet }} ${{ matrix.set }} (keycloak=${{ matrix.keycloak_version }} full=${{ matrix.keycloak_full }})'
  acceptance_matrix:
    set:
      - centos-7
      - centos-8
      - debian-9
      - debian-10
      - ubuntu-1804
    puppet:
      - puppet5
      - puppet6
    keycloak_version:
      - '8.0.1'
      - '10.0.1'
    keycloak_full: ['no']
  acceptance_includes:
    - set: centos-7
      puppet: puppet5
      keycloak_version: 8.0.1
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet5
      keycloak_version: 10.0.1
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet6
      keycloak_version: 8.0.1
      keycloak_full: 'yes'
    - set: centos-7
      puppet: puppet6
      keycloak_version: 10.0.1
      keycloak_full: 'yes'
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/centos-6.yml:
  delete: true
spec/acceptance/nodesets/centos-8.yml:
  image: centos:8.1.1911
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  packages:
    - iproute2
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  packages:
    - iproute2
